export const StateLabels = {
    OFF: 'OFF',
    EXIT_ROUND: 'EXIT ROUND',
    GAME_CRASHED: 'CRASHED AT:',
    GAME_STARTED: 'GAME STARTED',
    TAKING_BETS: 'TAKING BETS',
    ROUND_IN_PROGRESS: 'ROUND IN PROGRESS',
}
